### ISSUE TITLE
Children see a new todo list

### ISSUE THREAD

**Issue by tonyhuang219** [tonyhuang219/CS555#4]
children see a todo list
- [ ] children select a date from a calendar
- [ ] Display the list of tasks to do
- [ ] Can mark a task as finished

![image](https://user-images.githubusercontent.com/40710752/196004421-ce791c78-0257-4570-a1fb-4a1d220060aa.png)
